// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/bracketcore/go-rest-api-template/app/controllers"
	"github.com/bracketcore/go-rest-api-template/app/repositories"
	"github.com/bracketcore/go-rest-api-template/app/services"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitUserRouter(db *gorm.DB) *UserRouter {
	userRepository := repositories.ProvideUserRepository(db)
	userService := services.ProvideUserService(userRepository)
	authController := controllers.ProvideAuthController(userService)
	usersController := controllers.ProvideUsersController(userService)
	userRouter := ProvideUserRouter(authController, usersController)
	return userRouter
}
